### ISSUE TITLE
Staff App

### ISSUE THREAD

**Issue by Scull19** [JohnBoahnerges/MSModApp#1]
# Mystical Survival Mod Application

Discord Username: 

Scull

Role you are applying for? 

Mod

What do you do? (Modder, Modpack Dev, Dev) 

Mod and mild dev work. 

Where did you hear about us? 

Bluu invited me to become a tester of the pack. 

Why do you want to have this role/ what can you contribute to us?

 I would like to have this role because I really enjoy to help others wether it be helping players or getting rid of the trouble makers that come with anything being online. I would be able to bring to the team my vast knowledge of mods and also my extensive experience with player support both with vocal communication and written in game and or on a forum.  

What experince do you have with mincraft mods? 

I played on a network (Mine Your Mind) that hosts around 15 or so mod packs at a given time I was very active (over 1,000 hours in under a year) I ended up playing thru 10 or more of the mod packs that were offered. Also became a staff member on the network and quit at the beginning of this year ending in a Senior staff position. I also have other experience from being staff and owning my own unmodded servers that I setup by myself.

 I AGREE to the terms of service

**Comment by JohnBoahnerges** [comment]
# Accepted
